[platformio]
src_dir = .
include_dir = .

[env:powerbank-bench-sensor]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
build_flags = -DBOARD_HAS_PSRAM
lib_deps =
  adafruit/RTClib@^2.1.4
  bblanchon/ArduinoJson@^7.0.0
  kosme/arduinoFFT@^2.0.4
build_src_filter = +<sensor_node.ino>
